### ISSUE TITLE
Support for running specific set of tags

### ISSUE THREAD

**Issue by cw-pragna-bandi** [annaet/cypress-tags#34]
Hi @annaet we are trying to run test cases with specific set of tags but failing
For eg.

it(['smoke','wip'],'Test case 1' => () .......

it(['wip'],'Test case 2' => () .......

We want to run only those test cases with ['smoke','wip'] tag, but with the current version, it runs both my test cases since the second one contains 'wip' tag which is present in the command.

Do we feature/command/workaround that will help us achieve our goal?

**Comment by VickyLund99** [comment]
@annaet: Would you be open if we make the change and submit a Pull Request?
I tried the below change and it seems to be working:

https://github.com/annaet/cypress-tags/blob/master/src/index.ts#L44
`const includeTest = isDescribeNode || includeTags.length === 0 || includeTags.every(tag => tags.includes(tag));`

I'll add a flag for this and test it thoroughly before submitting a Pull Request.

**Comment by annaet** [comment]
Hi @cw-pragna-bandi 

Currently the implementation is intended to run any test that matches any of the existing tags passed in (a boolean OR rather than a boolean AND). I wouldn't want to change this functionality as it would act as a breaking change.

It's possible we could add this as a setting that could be controlled via a new environment variable. An alternative in the short term would be to create a new tag for your tests, eg. `smoke-wip` which would allow you to have a unique tag for those specific tests you wish to run.

**Comment by cw-pragna-bandi** [comment]
@annaet Hey, are you planning to implement this in coming release. We are open to helping you out.

**Comment by annaet** [comment]
Hi @cw-pragna-bandi, 

I've just released v0.1.0 of cypress-tags and it now includes environment variables to do the behaviour you've requested.

If you use the environment variables `CYPRESS_INCLUDE_USE_BOOLEAN_AND=true` and `CYPRESS_EXCLUDE_USE_BOOLEAN_AND=true` you will be able to control this behaviour for include, and exclude separately.

Please let me know if you have any issues with this after upgrading.
